name: send-results-to-testrail
on: [workflow_dispatch]
jobs:
  buildAndTest: # Название
    runs-on: ubuntu-latest # ОС на которой запускаемся
    steps: # Шаги выполнения
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install, build, test # Выполняем необходимые команды
        run: npm install -g newman
      - name: run newman # Выполняем необходимые команды
        run: newman run TestRail.postman_collection2.json -r cli,junit --reporter-junit-export newman_junit.xml
      - name: TestRail
        run: pip install trcli
      - name: upload results
        run: | 
          trcli -y \
          -h https://testdixma.testrail.io/ \
          --project "Test" \
          -u mrdixma@gmail.com \
          -p 'KO$dg5TN(xp0' \
          parse_junit \
          --title "Automated Tests from GitHub workflow" \
          --run-description ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} \
          -f "newman_junit.xml"


          
