name: send-results-to-testrail
on: [workflow_dispatch]
jobs:
  buildAndTest: # Название
    runs-on: ubuntu-latest # ОС на которой запускаемся
    steps: # Шаги выполнения
    - uses: actions/checkout@v1 
    - name: Use Node.js 8.x # Установим ноду
      uses: actions/setup-node@v1

    - name: Install, build, test # Выполняем необходимые команды
      run: |
        npm install -g newman \
        newman run TestRail.postman_collection.json

          
